### PR TITLE
Fix pages

### PR DESCRIPTION
**Pull request by maorninja322**
It didn't look nice. This shall do it

### CODE REVIEW

**Comment by 8JeDaYoshi8** [comment]
This repo is dead, maor322. :|

**Comment by LifeMushroom** [comment]
I don't know what this does and what changes, but i'll trust you on this.

**Comment by StapleButter** [comment]
So cool, moron322 can code. OMG.

**Comment by LifeMushroom** [comment]
@StapleButter 
plz

**Comment by StapleButter** [comment]
So it's okay if it's Jeda, but NOT OKAY if it's maor? What the fuck? Both
are equally dumb.

**Comment by Hennamann** [comment]
Not trying to ruin the mood even more, but there were reasons for me doing things like i did in downloads.php, not that i care much for it anymore of course...

**Comment by LifeMushroom** [comment]
Blah. I liked the former one better. Reverted.

**Comment by maor322** [comment]
@StapleButter STFU you moron. You do not know how to code. You only do some copy-pasta and slap your stupid name. So You are just MoronButter and please staple your butt.

**Comment by Hennamann** [comment]
Yes, cause blargboard is the only thing Staplebutter made...

**Comment by LifeMushroom** [comment]
Do you guys really need to fight lol

**Comment by Hennamann** [comment]
Nope not really, just felt like it...

**Comment by StapleButter** [comment]
@maor322 ahahahahahahahahahahahahahahahahahahahahahahahahaha

The stupidity has reached such a level that I won't even bother replying

**Comment by MrRean** [comment]
this commit is actually pretty dumb...uh...
also maor StapleButter coded his own stuff, what are you talking about lol

**Comment by LifeMushroom** [comment]
Yeah.

**Comment by Hennamann** [comment]
@LifeMushroom You should consider locking it, as of right now it's pointless to keep it open

**Comment by StapleButter** [comment]
Or alternately wait for maor322 to give us more hilarity.

**Comment by Hennamann** [comment]
I support both. lol

**Comment by LifeMushroom** [comment]
I already closed this. You can't really lock it.

**Comment by LifeMushroom** [comment]
Oh, wait.

**Pull request merged**
